---
- name: Check if arm platform is requested for an unsupported Splunk Release Version
  ansible.builtin.fail: |
    msg="Exiting.  Splunk for ARM install via Package is only supported on release 9.0.2 or later"
  when: splunk_release is version('9.0.2', 'lt', version_type='loose')

- name: Create Splunk group
  ansible.builtin.group:
    name: "{{ splunk_forwarder_group }}"
    gid: "{{ splunk_forwarder_gid }}"
    state: present
  tags: splunk_user

- name: Create Splunk user
  ansible.builtin.user:
    name: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
    uid: "{{ splunk_forwarder_uid }}"
    state: present
  tags: splunk_user

- name: Check if Splunk is installed
  ansible.builtin.stat:
    path: /opt/splunkforwarder/bin/splunk
  register: splunk_installed

- name: Check Splunk Universal Forwarder Version Installed
  # -auth :{{ splunk_forwarder_admin_pass }}
  ansible.builtin.shell: |
      set -o pipefail
      if [ -f /opt/splunkforwarder/bin/splunk ]; then
        /opt/splunkforwarder/bin/splunk --accept-license --answer-yes -version |tail -1 |cut -d ' ' -f 4
      fi
  args:
    executable: /bin/bash
  register: splunk_version_check
  changed_when: splunk_version_check.stdout != splunk_release

- name: Install role package dependencies
  ansible.builtin.package:
    name: acl
    state: present

- name: Install Splunk Forwarder Client
  when: splunk_version_check.stdout != splunk_release
  notify:
    - Enable Splunk Forwarder
    - Clear config for Cloning
  block:

    - name: Install Splunk Forwarder on Debian
      ansible.builtin.include_tasks:
        file: debian.yml
      when: ansible_os_family == "Debian"

    - name: Install Splunk Forwarder on RHEL
      ansible.builtin.include_tasks:
        file: rhel.yml
      when: ansible_os_family == "RedHat"

- name: "Find all directories within $SPLUNK_HOME"
  ansible.builtin.find:
    path: "{{ splunk_home }}"
    file_type: any
    recurse: true
  register: splunk_contents
  when: not splunk_installed.stat.exists and splunk_forwarder_user != "splunkfwd"

- name: "Recursively change ownership of $SPLUNK_HOME"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
  loop: "{{ splunk_contents.files }}"
  when: not splunk_installed.stat.exists and splunk_forwarder_user != "splunkfwd"

- name: Copy user seeds file
  ansible.builtin.template:
    src: user-seed.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_admin_user is defined and splunk_forwarder_admin_pass is defined
  tags: config_copy

- name: Copy deployment client file
  ansible.builtin.template:
    src: deploymentclient.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_depl_server is defined
  tags: config_copy

- name: Copy inputs file
  ansible.builtin.template:
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    mode: 0664
    backup: true
  tags: config_copy

- name: Copy outputs file
  ansible.builtin.template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    mode: 0664
    backup: true
  tags: config_copy

- name: Copy server file
  ansible.builtin.template:
    src: server.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/server.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_output_use_tls
  tags: config_copy

- name: Set logfile permissions
  ansible.posix.acl:
    path: "{{ item.path }}"
    entity: "{{ splunk_forwarder_user }}"
    state: present
    etype: user
    permissions: r
    recursive: true
  become: true
  with_items: "{{ splunk_forwarder_logs }}"

- name: Accept Splunk License
  ansible.builtin.command: "/opt/splunkforwarder/bin/splunk enable boot-start -systemd-managed 1 -user {{ splunk_forwarder_user }} -group {{ splunk_forwarder_group }} --accept-license --answer-yes --no-prompt"
  when: not splunk_installed.stat.exists
