---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    requirements-file: collections.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance-1
    image: "${TEST_MOLECULE_DISTRO}"
    # We cannot specify platform without breaking
    # tests on armv8
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: ansible
